version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 10

  # Maintain dependencies for Go
  - package-ecosystem: gomod
    directory: /go
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 10

  # Maintain dependencies for Python
  - package-ecosystem: pip
    directory: /python
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 10

  # Maintain dependencies for Rust
  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 10

  # Maintain dependencies for TypeScript
  - package-ecosystem: npm
    directory: /typescript
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 10
    groups:
      eslint:
        patterns:
          - '*eslint*'
    ignore:
      - dependency-name: '@types/node'
        versions: ['>20.11']
